[package]
name = "abcd-file"
edition.workspace = true
version.workspace = true

[dependencies]
abcd-isa = { workspace = true }
abcd-file-sys = { workspace = true }
thiserror = { workspace = true }
memmap2 = { workspace = true }
log = { workspace = true }
